ALTER TABLE `AuditLog` MODIFY `action` ENUM(
  'CELL_UPDATED',
  'CELL_FORMAT_UPDATED',
  'ROW_CLAIMED',
  'ROW_UNLOCKED',
  'COLUMN_PERMISSION_UPDATED',
  'VALIDATION_RULE_UPDATED',
  'CONDITIONAL_RULE_UPDATED',
  'SHEET_VIEW_UPDATED',
  'AUDIT_HISTORY_CLEANED',
  'USER_SIGNED_IN'
) NOT NULL;
